### ISSUE TITLE
how to solve this problem?

### ISSUE THREAD

**Issue by Steven-Xiong** [kirillProkofiev/light-weight-face-anti-spoofing#18]
While training python train.py --config configs/config.py , I meet this problem:

Traceback (most recent call last):
  File "train.py", line 150, in <module>
    main()
  File "train.py", line 55, in main
    train(config, device, args.save_checkpoint)
  File "train.py", line 101, in train
    train_dataset, val_dataset, test_dataset = make_dataset(config, train_transform, val_transform)
  File "/home/xiongzhexiao/light-weight-face-anti-spoofing-master/utils.py", line 177, in make_dataset
    datasets = get_datasets(config)
  File "/home/xiongzhexiao/light-weight-face-anti-spoofing-master/datasets/database.py", line 67, in get_datasets
    'external_train': partial(external_reader, **config.external.train_params),
  File "/home/xiongzhexiao/anaconda3/lib/python3.8/site-packages/attrdict/mixins.py", line 80, in __getattr__
    raise AttributeError(
AttributeError: 'AttrDict' instance has no attribute 'train_params'
I have changed the root dir of the three datasets.

**Comment by beyza-yildirim** [comment]
Were you able solve this?

**Comment by manhdoan291** [comment]
i have a same problem ? how to solve it

**Comment by manhdoan291** [comment]
error is easy. I have fixed. you can ignore 'external_train': partial(external_reader, **config.external.train_params)
